use_frameworks!

target 'ColorPicker_Example' do
  platform :macos
  pod 'ColorPicker', :path => '../'

  target 'ColorPicker_Tests' do
    inherit! :search_paths
    pod 'ColorPicker', :path => '../'
  end
end
