use_frameworks!

target 'ColorPicker_Example' do
  platform :macos, '10.12'
  pod 'macColorPicker', :path => '../'

  target 'ColorPicker_Tests' do
    inherit! :search_paths
    pod 'macColorPicker', :path => '../'
  end
end
